config/routes.rb
Rails.application.routes.draw do

  get 'carts/:id'=> "carts#show", as: "cart"
  get 'carts/:id/add' => "carts#add_product", as: "cart_add"
  get 'carts/:id/reduce' => "carts#reduce_quantity", as: "cart_reduce"
  resources :carts, only: :destroy

  get 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  get 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  delete 'line_items/:id' => "line_items#destroy", as: "line_item_erase"

  resources :orders, only: [:index, :show, :new, :create]
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks" }
  root to: "pages#home"
  resources :pages, only:[:index, :create]

  resources :products
end

app/models/cart.rb
class Cart < ApplicationRecord
  has_many :line_items, dependent: :destroy
  has_many :products, through: :line_items


  def sub_total
    sum = 0
    self.line_items.each do |line_item|
      sum += line_item.total_price
    end
    return sum
  end

  def sum_total
    sum = 0
    self.line_items.each do |line_item|
      sum += line_item.total_items
    end
    return sum
  end

  def add_product(product)
    current_item = line_items.find_by(product_id: product.id)
    if current_item
      current_item.quantity += 1
    else
      current_item = line_items.build(product_id: product.id)
    end
    current_item
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  def show
    @cart = Cart.find(params[:id])
  end

  def destroy
    @cart = Cart.find(params[:id])
    @cart.destroy
    session[:cart_id] = nil
    redirect_to root_path
  end
end

app/views/carts/show.html.erb
<div class="container py-5">
  <div class="container py-5">
    <div class="container-carrito">
      <div class="row">
        <div class="col-12 mx-3">
          <div class="row">
            <div class="col-12">
              <h1 class="Shopping-Cart text-center"> <strong> Carrito de Compra </strong></h1>
            </div>
          </div>
        </div>
        <div class="row">
          <% @cart.line_items.each do |line_item| %>
            <div class="col-12 col-lg-3">
              <%= cl_image_tag line_item.product.photos.last.key, crop: :fill, class: "image-box" %>
            </div>
            <div class="col-12 col-lg-6">
              <h3 class="text-left pt-5"> <%= line_item.product.name %> </h3>
            </div>
            <div class="col-12 col-lg-2">
              <div class="d-flex flex-box justify-content-between pt-4">

                    <%= link_to " - ", line_item_reduce_path(line_item) %>
                    <h5> <%= line_item.quantity %> </h5>
                    <%= link_to " + ", line_item_add_path(line_item) %>

                    <h4> <%= number_to_currency(line_item.product.price) %> </h4>

              </div><br>
              <%= link_to "Remover elemento", line_item_erase_path(line_item),
              data: { turbo_method: :delete, turbo_confirm: "¿Deseas eliminar este item?" } %>
            </div>
            <div class="">
        <hr class="mx-3 w-100">
            </div><br>
          <% end %>
        </div>
        <div class="row">
          <div class="col-9">
          </div>
          <div class="col-3">
            <div class="d-flex justify-content-center">
              <h4>  <%= number_to_currency(@cart.sub_total) %> </h4>
            </div>
            <div class="d-flex justify-content-center">
              <h4> <%= @cart.sum_total %> items </h4>
            </div> <br>
            <div class="d-flex justify-content-left">
            <% if @cart.sub_total > 0 %>
              <%= link_to "Comprar", new_order_path, class: "btn btn-ghost w-100 " %>
            <% else %>
              <%= link_to "Comprar", products_path, class: "btn btn-ghost w-100 " %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/carts/show2.html.erb
<head>
	<title>Shopping Cart UI</title>
	<link rel="stylesheet" type="text/css" href="./style.css">
	<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,900" rel="stylesheet">
</head>
  <body>
    <div class="super py-5 mt-3">
      <div class="CartContainer">
          <div class="Header">
            <h3 class="Heading">Shopping Cart</h3>
              <%= render "shared/cartsidebar" %>
            <h3 class="Heading">
              <%= link_to "Vaciar Carrito", cart_path(@cart),
                data: { turbo_method: :delete, turbo_confirm: "Estas seguro de vaciar el carrito?" }
            %>
            </h3>
          </div>
          <% @cart.line_items.each do |line_item| %>
            <div class="Cart-Items">
                <div >
                 <%# line_item.product.photos.each do |photo| %>
                  <%#= cl_image_tag photo.key, height: 120, width: 500, crop: :pad  %>
                  <%= cl_image_tag line_item.product.photos.last.key, crop: :fill, class: "image-box" %>
                 <%#end %>
                </div>
                <div class="about">
                  <h1 class="title"><%= line_item.product.name %></h1>
                </div>
                <div class="counter">
                  <div class="btn"><%= link_to "-", line_item_reduce_path(line_item) %></div>
                  <div class="count"><%= line_item.quantity %></div>
                  <div class="btn" ><%= link_to "+", line_item_add_path(line_item)%></div>
                </div>
                <div class="prices">
                  <div class="amount"><%= number_to_currency(line_item.product.price) %></div>
                  <%= link_to "Remover elemento",
                    line_item_erase_path(line_item),
                    data: {turbo_method: :delete, turbo_confirm: "Deseas elimninar este item?"}
                  %>
                </div>
            </div>
          <% end %>
<hr>
        <div class="checkout">
        <div class="total">
          <div>
            <div class="Subtotal"><%= number_to_currency(@cart.sub_total) %></div>
            <div class="items"><%= @cart.sum_total %> items</div>
          </div>
          <div class="total-amount"></div>
        </div>
        <div class="py-3">
          <button class="btn btn-ghost"><%= link_to "Comprar", new_order_path %></button>
        </div>
        </div>
      </div>
    </div>
  </body>