config/routes.rb
Rails.application.routes.draw do

  get 'carts/:id'=> "carts#show", as: "cart"
  get 'carts/:id/add' => "carts#add_product", as: "cart_add"
  get 'carts/:id/reduce' => "carts#reduce_quantity", as: "cart_reduce"
  resources :carts, only: :destroy

  get 'line_items/:id/add' => "line_items#add_quantity", as: "line_item_add"
  get 'line_items/:id/reduce' => "line_items#reduce_quantity", as: "line_item_reduce"
  post 'line_items' => "line_items#create"
  delete 'line_items/:id' => "line_items#destroy", as: "line_item_erase"

  resources :orders, only: [:index, :show, :new, :create]
  devise_for :users, controllers: {
    omniauth_callbacks: "omniauth_callbacks" }
  root to: "pages#home"
  resources :pages, only:[:index, :create]

  resources :products
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  belongs_to :user
  has_many :line_items
  has_many_attached :photos

  before_update :actualiza_descuento
  before_save :actualiza_descuento

    # SE AGREGO PARA EL SEARCH DEL NAVBAR

  include PgSearch::Model
  pg_search_scope :search_products, against: [ :name, :description ],
    using: {
        tsearch: {
          prefix: true
          }
      }

  # validar que todos lo campos no esten vacios al crear
  validates :name, :original_price, :discount, :stock, :description, :photos, presence: true

  # validacion para :name
  validates :name, length: { minimum: 10, message: "Debe de tener más de 10 caracteres" }

  # validacion para :original_price
  validates :original_price, numericality: { only_float: true, message: "Tiene que ser número" }
  validates :original_price, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 9999 }
  # validates :original_price, format: { with: /[0-9]*/, message: "solo numeros" }

  # validacion para :discount
  validates :discount, numericality: { only_integer: true }
  validates :discount, numericality: { greater_than_or_equal_to: 1, less_than_or_equal_to: 100 }

  # validacion para :stock
  validates :stock, numericality: { only_integer: true }
  validates :stock, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 9999 }

  # validacion para :description
  validates :description, length: { minimum: 10, maximum: 1000, message: "Debe de tener más de 10 caracteres" }

  private

  def actualiza_descuento
    self.price = (
      self.original_price - (self.original_price * self.discount) / 100
    )
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_products, only: %w[show edit update destroy]
  skip_before_action :authenticate_user!, only: %i[index show]

  def index
    if params[:query].present?
      if @products = Product.search_products(params[:query])
        @products = Product.search_products(params[:query])
      else
        @products = Product.all
      end
      # elsif params[:query].empty?
      # redirect_to root_path
      # flash[:notice] = "no se encontro datos"
    elsif params[:category_id].present?
      @products = Product.where(category_id: params[:category_id])
    else
      @products = Product.all
    end
  end

  def show
  end

  def new
    if current_user.ruc.nil?
      redirect_to edit_user_registration_path(current_user.id)
      flash[:notice] = "Debe tener 'RUC' en los datos para vender"
    else
      @product = Product.new
    end
  end

  def create
    @product = Product.new(products_params)
    @product.user_id = current_user.id
    @product.expiration_date = "" if @product.category != 2 && @product.category != 4
    if @product.save
      redirect_to product_path(@product)
      flash[:notice] = "Producto creada con éxito"
    else
      render :new, status: :unprocessable_entity
      flash[:notice] = "ERROR - Revise los datos a registrar para crear el Producto"
    end
  end

  def edit
    if current_user.ruc.empty?
      redirect_to edit_user_registration_path(current_user.id)
      flash[:notice] = "Debe vendedor para esa acción"
    else
      @category = Category.new
      @product = Product.find(params[:id])
    end
  end

  def update
    @product = Product.find(params[:id])
    @product.update!(products_params)
    redirect_to product_path(@product)
    flash[:notice] = "Producto actualizado con éxito"
  end

  def destroy
    @product = Product.find(params[:id])
    if @product.line_items.any?
      redirect_to product_path(@product)
      flash[:notice] = "Eliminar primero del carrito "
    else
      @product.destroy
      redirect_to products_path, status: :see_other
      flash[:notice] = "Producto eliminado con éxito"
    end
  end

  private

  def set_category
    @category = Category.find(params[:id])
  end

  def set_products
    @product = Product.find(params[:id])
  end

  def products_params
    params.require(:product).permit(
      :name, :original_price, :discount, :stock, :expiration_date, :description,
      :category_id, :user_id, photos: []
    )
  end
end

app/views/products/edit.html.erb
<div class="container py-5">
  <div class="container pt-5">
    <div class="container pt-4">
      <div class="container-pro-new">
        <div class="row">
          <div class="col-6">
          <h1 class="text-center rounded pt-3 pb-1"><strong> Editar Producto </strong></h1>
            <%= simple_form_for (@product) do |f| %>
            <div class="row">
              <% current_user.ruc.empty? %>
              <div class="col-12 col-lg-6 pt-3 ">
                <%= f.association :category, label: "Categoria del Producto:", prompt: "Categoría del Producto" %>
              </div>
              <div class="col-12 col-lg-6 pt-3">
                <%= f.input :name, label: "Nombre del Producto:", placeholder: "Nombre del producto", required: true %>
              </div>
              <div class="col-12 col-lg-6 ">
                <%= f.input :original_price, as: :string, label: "Precio Real del Producto:", placeholder: "Precio original del producto", required: true %>
              </div>
              <div class="col-12 col-lg-6 ">
                <%= f.input :discount, as: :string, label: "Descuento del Producto:", placeholder: "Descuento del producto", required: true %>
              </div>
              <div class="col-12 col-lg-6 ">
                <%= f.input :stock, as: :string, label: "Stock del Producto:", placeholder: "Stock del Producto", required: true %>
              </div>
              <div class="col-12 col-lg-6 ">
                <%= f.input :expiration_date, html5: true, label: "Fecha de Expiración:" %>
              </div>
            </div>
            <div>
              <%= f.input :description, label: "Descripción del Producto:", placeholder: "Descripcion del producto", required: true %>
            </div>
            <div>
              <%= f.input :photos, label: "Imagen a cargar", as: :file, input_html: { multiple: true }, required: true %>
            </div>
            <div class="d-flex justify-content-around pt-3 pb-5">
              <%= f.submit "Enviar", class: "btn btn-ghost pb-3" %>
              <%= link_to "Salir", products_path, class: "btn btn-ghost" %>
            </div>
            <% end %>
          </div>
          <div class="col-6">
            <div>
              <%= image_tag "pla_net.jpeg", class:"imagen-pro-new" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/index.html.erb
<div class="container py-5">
  <div class="container py-5">
    <div class="product_container py-4 row">
      <% @products.each do |product| %>
        <div class="col-sm-12 col-lg-6 col-xxl-4 mb-2">
          <% unless product.stock.zero? %>
            <div class="card-trip-product py-3">
              <% if product.stock.to_i < 15 %>
                <p>Últimas <%= product.stock %> Unds.</p>
              <% end %>
              <% product.photos.last(1).each do |photo| %>
                <%= link_to product_path(product) do %>
                  <%= cl_image_tag photo.key, crop: :pad, class: "imagen-index" %>
                <% end %>
              <% end %>
              <div class="card-trip-infos mx-3">
                <div>
                  <h2> <%= number_to_currency(product.original_price) %></h2>
                  <h3> <%= number_to_currency(product.price) %></h3>
                  <h4><%= product.name.truncate(40) %> </h4>
                    <% if product.expiration_date.present? %>
                      <h5>Vencimiento: <%= product.expiration_date %></h5>
                    <% else %>
                      <h5><br></h5>
                    <% end %>
                </div>
                <h6 class="badge rounded-pill h1"> -<%= product.discount %>% </h6>
              </div>
              <div class="text-center pb-3">
                <% if user_signed_in? && current_user.id == product.user_id %>
                  <%= link_to "Editar", edit_product_path(product), class: "btn btn-ghost" %>
                  <%= link_to "Eliminar", product_path(product), class: "btn btn-ghost", data:
                  {turbo_method: :delete, turbo_confirm: "¿Estás seguro de eliminar el producto?"} %>
                <% else %>
                  <% if product.stock.to_i > 0 %>
                      <%= form_tag line_items_path do %>
                        <%= hidden_field_tag 'product_id', product.id %>
                        <%= hidden_field_tag 'current_cart_id', @current_cart.id %>
                        <%= submit_tag 'Agregar', class: "btn btn-ghost" %>
                      <% end %>
                  <% else %>
                      <%= link_to "Ver otros productos", root_path, class: "btn btn-ghost" %>
                  <% end %>
                <% end %>
              </div>
            </div>
          <% end %>
        </div>
      <% end %>
    </div>
    <div class="container text-center py-2">
      <h4 class="py-4">¿Quieres vender tus productos con nosotros?</h4>
      <%= link_to "¡Sí!", new_product_path, class: "btn btn-ghost" %>
    </div>
  </div>
</div>

app/views/products/new.html.erb
<div class="container py-5">
  <div class="container pt-5">
    <div class="container pt-4">
      <div class="container-pro-new">
        <div class="row">
          <div class="col-6">
            <h1 class="text-center pt-2 pb-2"><strong> Registro de Producto </strong></h1>
              <%= simple_form_for (@product) do |f| %>
                <div class="row">
                  <%# current_user.ruc.empty? %>
                  <div class="col-12 col-lg-6 pt-3 ">
                    <%= f.association :category, label: "Categoria del Producto:", prompt: "Categoría del Producto" %>
                  </div>
                  <div class="col-12 col-lg-6 pt-3">
                    <%= f.input :name, label: "Nombre del Producto:", placeholder: "Nombre del producto", required: true %>
                  </div>
                  <div class="col-12 col-lg-6 ">
                    <%= f.input :original_price, as: :string, label: "Precio Real del Producto:", placeholder: "Precio original del producto", required: true %>
                  </div>
                  <div class="col-12 col-lg-6 ">
                    <%= f.input :discount, as: :string, label: "Descuento del Producto:", placeholder: "Descuento del producto", required: true %>
                  </div>
                  <div class="col-12 col-lg-6 ">
                    <%= f.input :stock, as: :string, label: "Stock del Producto:", placeholder: "Stock del Producto", required: true %>
                  </div>
                  <div class="col-12 col-lg-6 ">
                    <%= f.input :expiration_date, html5: true, label: "Fecha de Expiración:" %>
                  </div>
                </div>
                <div class="">
                  <%= f.input :description, label: "Descripción del Producto:",
                  placeholder: "Descripcion del producto", required: true %>
                </div>
                <div class="">
                  <%= f.input :photos, label: "Imagen a cargar", as: :file,
                  input_html: { multiple: true }, required: true %>
                </div>
                <div class="d-flex justify-content-around pt-3 pb-5">
                  <%= f.submit "Enviar", class: "btn btn-ghost pb-3" %>
                  <%= link_to "Salir", products_path, class: "btn btn-ghost" %>
                </div>
              <% end %>
          </div>
          <div class="col-6">
            <div class="">
              <%= image_tag "pla_net.jpeg", class:"imagen-pro-new" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/products/show.html.erb
<div class="container py-5 mt-3">
  <div class="container py-5">
    <div class="card-product-show">
      <% @product.photos.last(1).each do |photo| %>
        <%= cl_image_tag photo.key, crop: :pad, class: "imagen-show mt-4"%>
      <% end %>
      <div class="card-product-infos-pro pe-5 w-80">
        <div class="label-stock">
          <% if @product.stock >=1 || @product.stock  < 15 %>
                Últimas <%= @product.stock %> Unds.
          <% elsif @product.stock > 15  %>
            <%= @product.stock %> Unds. Disponibles.
          <% else %>
            Sin Stock.
          <% end %>
        </div>
        <h1><%= @product.name %></h1>
        <h2><%= @product.description %></h2>
        <% if @product.expiration_date.present? %>
          <h3>Vencimiento: <strong><%= @product.expiration_date %></strong></h3>
        <% else %>
          <h3> <br> </h3>
        <% end %>
          <div class="d-flex justify-content-between align-items-end">
            <div>
              <h4> <%= number_to_currency(@product.original_price) %></h4>
              <h5> <%= number_to_currency(@product.price) %> </h5>
            </div>
            <div>
              <h6 class="badge rounded-pill"> -<%= @product.discount %>% </h6>
            </div>
          </div>
          <p class="py-3 pb-3"> <span class="badge rounded-pill text-bg-warning">!</span>
            Este producto puede presentar defectos en su presentación,
            sin embargo su calidad y funcionalidad no se ven afectadas.</p>
          <div class="text-center">
            <% if user_signed_in? && current_user.id == @product.user_id %>
              <%= link_to "Editar", edit_product_path(@product), class: "btn btn-ghost" %>
              <%= link_to "Eliminar", product_path(@product), class: "btn btn-ghost",
              data: {turbo_method: :delete, turbo_confirm: "¿Estás seguro de eliminar el producto?"} %>
            <% else %>
              <% if @product.stock.to_i > 0 %>
                <%= form_tag line_items_path do %>
                  <%= hidden_field_tag 'product_id', @product.id %>
                  <%= hidden_field_tag 'current_cart_id', @current_cart.id %>
                  <%= submit_tag 'Agregar', class: "btn btn-ghost" %>
                <% end %>
              <% else %>
                <%= link_to "Ver otros productos", root_path, class: "btn btn-ghost" %>
              <% end %>
              <%#= link_to "Comprar", cart_path(@current_cart), class: "btn btn-ghost" %>
            <% end %>
          </div>
  </div>
</div><br>